### PR TITLE
Update nuget packages

### PR DESCRIPTION
**Pull request by SvenVandenbrande**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
The reason the tests fail is because the NUnit 3.5 console runner has decided that it is an error if a test DLL does not contain any tests.

Newer versions of Rebus.Tests.Contracts have a Dummy test to dodge this error.

Could you update the Rebus.Tests.Contracts so that the tests pass?

**Comment by SvenVandenbrande** [comment]
Yes, will do it this evening. :)
Late checking yesterday evening, did a rebuild locally. But didn't run the tests.... :)

**Comment by SvenVandenbrande** [comment]
@mookid8000 I checked it again. But we have already the latest version...

**Comment by mookid8000** [comment]
Hi Sven, I think I have figure out why the tests are failing – for some reason, NUnit 3.5 seems to fail with the "the assembly has no testfixtures" error when the assembly contains non-abstract classes with `[Test]`-decorated methods but no `[TestFixture]` attribute – which is what Rebus.Tests.Contracts used to have.

I have fixed that in 3.0.0-beta03 though – could you try and update to that and then we will see if the tests run?

**Comment by SvenVandenbrande** [comment]
@mookid8000 Done :)

**Comment by mookid8000** [comment]
nice work 😄 I will downgrade to 3.5.1 though because 3.5.2-patch-35181 is a prerelease version and thus would require that the Rebus.RavenDb package also be released as a prerelease version

**Comment by mookid8000** [comment]
it's out as 2.1.0 on NuGet.org now 😄

**Pull request merged**
